name: pr-gate
on:
  pull_request:
jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Require CODEOWNERS approval
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pull_number = context.payload.pull_request.number;
            const {data: pr} = await github.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });

            const pendingUsers = pr.requested_reviewers?.map((reviewer) => `@${reviewer.login}`) ?? [];
            const pendingTeams = pr.requested_teams?.map(
              (team) => `@${team.organization.login}/${team.slug}`,
            ) ?? [];

            if (pendingUsers.length === 0 && pendingTeams.length === 0) {
              core.notice('All required reviewers have approved.');
              return;
            }

            const pending = [...pendingUsers, ...pendingTeams];
            core.setFailed(
              `Awaiting required review from: ${pending.join(', ')}`,
            );
      - name: Block auto-merge (informational)
        run: |
          echo "Auto merge is disabled by policy"
          exit 0
