name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Run frontend tests
        run: npm run test

  rust:
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install GTK dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libgtk-3-dev libglib2.0-dev libgdk-pixbuf-2.0-dev libpango1.0-dev libsoup2.4-dev libwebkit2gtk-4.1-dev libappindicator3-dev

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint with clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test

  completion:
    runs-on: ubuntu-latest
    needs:
      - frontend
      - rust
    if: ${{ always() }}
    steps:
      - name: Report status
        run: |
          if [[ "${{ needs.frontend.result }}" != 'success' || "${{ needs.rust.result }}" != 'success' ]]; then
            echo 'One or more jobs failed'
            exit 1
          fi
          echo 'All checks succeeded'
