name: test

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: UTC
  LANG: C.UTF-8

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p workflow-cookbook/logs
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: ESLint
        run: |
          set -Eeuo pipefail
          if [ -f package.json ]; then
            start=$(date +%s%3N)
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
            if node -e "p=require('./package.json');process.exit(!(p.scripts&&p.scripts.lint))"; then
              if npm run -s lint; then s=pass; else s=fail; fi
            else
              if npx eslint .; then s=pass; else s=fail; fi
            fi
            echo "{\"name\":\"lint\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
          else
            echo "{\"name\":\"lint\",\"status\":\"skip\",\"duration_ms\":0}" >> workflow-cookbook/logs/test.jsonl
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-logs-${{ github.job }}'
          path: workflow-cookbook/logs/*

  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p workflow-cookbook/logs
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Prettier
        run: |
          set -Eeuo pipefail
          if [ -f package.json ]; then
            start=$(date +%s%3N)
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
            if npx prettier --check .; then s=pass; else s=fail; fi
            echo "{\"name\":\"format\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
          else
            echo "{\"name\":\"format\",\"status\":\"skip\",\"duration_ms\":0}" >> workflow-cookbook/logs/test.jsonl
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-logs-${{ github.job }}'
          path: workflow-cookbook/logs/*

  typecheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p workflow-cookbook/logs
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: TypeScript (if exists)
        run: |
          set -Eeuo pipefail
          if [ -f tsconfig.json ]; then
            start=$(date +%s%3N)
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
            if npx tsc --noEmit; then s=pass; else s=fail; fi
            echo "{\"name\":\"typecheck\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
          else
            echo "{\"name\":\"typecheck\",\"status\":\"skip\",\"duration_ms\":0}" >> workflow-cookbook/logs/test.jsonl
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-logs-${{ github.job }}'
          path: workflow-cookbook/logs/*

  unit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p workflow-cookbook/logs
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Node unit (repo root)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          set -Eeuo pipefail
          start=$(date +%s%3N)
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi
          if CI=1 npm test --silent; then s=pass; else s=fail; fi
          echo "{\"name\":\"node::root\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
      - name: Node unit (frontend/)
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: frontend
        run: |
          set -Eeuo pipefail
          start=$(date +%s%3N)
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi
          if CI=1 npm test --silent; then s=pass; else s=fail; fi
          echo "{\"name\":\"node::frontend\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> ../workflow-cookbook/logs/test.jsonl
      - name: Node unit (packages/*)
        if: ${{ hashFiles('packages/*/package.json') != '' }}
        run: |
          set -Eeuo pipefail
          shopt -s nullglob
          for PKG in packages/*; do
            if [ -f "$PKG/package.json" ]; then
              pushd "$PKG" >/dev/null
              start=$(date +%s%3N)
              if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
                npm ci
              else
                npm install --no-audit --no-fund
              fi
              if CI=1 npm test --silent; then s=pass; else s=fail; fi
              popd >/dev/null
              echo "{\"name\":\"node::${PKG}\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
            fi
          done
          shopt -u nullglob
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Pytest (repo root)
        if: ${{ hashFiles('pyproject.toml') != '' || hashFiles('requirements*.txt') != '' || hashFiles('requirements/*.txt') != '' }}
        run: |
          set -Eeuo pipefail
          python -m pip install -U pip wheel || true
          python -m pip install -r requirements.txt 2>/dev/null || true
          python -m pip install -r requirements/dev.txt 2>/dev/null || true
          python -m pip install pytest || true
          start=$(date +%s%3N)
          if pytest -q; then s=pass; else s=fail; fi
          echo "{\"name\":\"python::root\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
      - name: Pytest (backend/)
        if: ${{ hashFiles('backend/pyproject.toml') != '' || hashFiles('backend/requirements*.txt') != '' }}
        working-directory: backend
        run: |
          set -Eeuo pipefail
          python -m pip install -U pip wheel || true
          python -m pip install -r requirements.txt 2>/dev/null || true
          python -m pip install -r requirements/dev.txt 2>/dev/null || true
          python -m pip install pytest || true
          start=$(date +%s%3N)
          if pytest -q; then s=pass; else s=fail; fi
          echo "{\"name\":\"python::backend\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> ../workflow-cookbook/logs/test.jsonl
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-logs-${{ github.job }}'
          path: workflow-cookbook/logs/*

  security:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p workflow-cookbook/logs
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: npm audit (moderate)
        run: |
          set -Eeuo pipefail
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            start=$(date +%s%3N)
            npm ci
            if npm audit --audit-level=moderate; then s=pass; else s=fail; fi
            echo "{\"name\":\"security\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
          else
            echo "{\"name\":\"security\",\"status\":\"skip\",\"duration_ms\":0}" >> workflow-cookbook/logs/test.jsonl
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-logs-${{ github.job }}'
          path: workflow-cookbook/logs/*

  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p workflow-cookbook/logs
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Coverage (if script exists)
        run: |
          set -Eeuo pipefail
          if [ -f package.json ] && node -e "p=require('./package.json');process.exit(!(p.scripts&&p.scripts.coverage))"; then
            start=$(date +%s%3N)
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
            if npm run -s coverage; then s=pass; else s=fail; fi
            echo "{\"name\":\"coverage\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
          else
            echo "{\"name\":\"coverage\",\"status\":\"skip\",\"duration_ms\":0}" >> workflow-cookbook/logs/test.jsonl
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-logs-${{ github.job }}'
          path: workflow-cookbook/logs/*

  build:
    needs: [lint, typecheck, unit]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p workflow-cookbook/logs dist
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Build (if exists)
        run: |
          set -Eeuo pipefail
          if [ -f package.json ] && node -e "p=require('./package.json');process.exit(!(p.scripts&&p.scripts.build))"; then
            start=$(date +%s%3N)
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
            if npm run -s build; then s=pass; else s=fail; fi
            echo "{\"name\":\"build\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
          else
            echo "{\"name\":\"build\",\"status\":\"skip\",\"duration_ms\":0}" >> workflow-cookbook/logs/test.jsonl
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-output
          path: dist/**
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-logs-${{ github.job }}'
          path: workflow-cookbook/logs/*

  e2e:
    needs: [build]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p workflow-cookbook/logs
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Playwright E2E (if exists)
        run: |
          set -Eeuo pipefail
          if [ -f package.json ] && node -e "p=require('./package.json');process.exit(!(p.scripts&&p.scripts['test:e2e']))"; then
            start=$(date +%s%3N)
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
            npx playwright install --with-deps
            if CI=1 npm run -s test:e2e; then s=pass; else s=fail; fi
            echo "{\"name\":\"e2e\",\"status\":\"$s\",\"duration_ms\":$(( $(date +%s%3N)-start ))}" >> workflow-cookbook/logs/test.jsonl
          else
            echo "{\"name\":\"e2e\",\"status\":\"skip\",\"duration_ms\":0}" >> workflow-cookbook/logs/test.jsonl
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'test-logs-${{ github.job }}'
          path: workflow-cookbook/logs/*

  report:
    needs: [lint, format, typecheck, unit, security, coverage, build, e2e]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: 'test-logs-*'
          path: logs
      - name: Summarize & STRICT gate (optional)
        run: |
          set -Eeuo pipefail
          files=$(find logs -name 'test.jsonl' | sort || true)
          if [ -z "$files" ]; then
            echo "No JSONL found"
            exit 0
          fi

          combined=logs/combined-test.jsonl
          : > "$combined"
          for f in $files; do
            cat "$f" >> "$combined"
          done

          echo "=== CI Summary (raw JSONL) ==="
          cat "$combined" || true

          fails=$(grep -c '"status":"fail"' "$combined" || true)
          echo "Fail count: $fails"

          if [ "${CI_STRICT:-}" = "true" ] && [ "$fails" -gt 0 ]; then
            echo "STRICT mode: failing due to failed statuses."
            exit 1
          fi
