name: tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          set -o pipefail
          mkdir -p artifacts
          RUST_BACKTRACE=1 CARGO_TERM_COLOR=always cargo test -- --nocapture | tee artifacts/cargo-test.log
      - name: Upload cargo test log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          path: artifacts/cargo-test.log
